### ISSUE TITLE
Bug Report | CD does not work & please add a wiki page

### ISSUE THREAD

**Issue by lundeen-bryan** [cherryamme/shellbook#1]
hello, I think this is a great idea, but I am finding it hard to implement. For example it doesn't run "cd" command. 

```
###
# 1. Navigate to Farm Folder
cd Farm/
###
```

Results in:
```
(base) bryan20@Len-mini:~/repos/3998050
▶ (###
> # 1. Navigate to Farm Folder
> cd Farm/
> ###
> )
(base) bryan20@Len-mini:~/repos/3998050
▶ 
```

Notice that I'm still in the parent folder and it didn't navigate to the "Farm" folder. 

Here is what it looks like when I manually enter the CD command:
```
▶ cd Farm/
(base) bryan20@Len-mini:~/repos/3998050/Farm
▶ 
```

---- Also 
I think this project would be a lot better with a wiki to explain some use cases.

**Comment by cherryamme** [comment]
Hello @lundeen-bryan 

Apologize for the delay in responding to your query and for any confusion you may have experienced in this project. 
I'm glad to clarify that the 'cd' command behaviour you observed is by design and not a bug.

The project you're using is intended to run code within chunks in an isolated subshell, which means that commands like "cd" do not affect the main shell environment. This design choice ensures that your current working directory in the main shell remains unchanged after executing code in a chunk. That's why you found yourself still in the parent directory after attempting to navigate to the "Farm" folder within the subshell. that's more like a command notebook that different with a quickly command snippets.

Regarding the suggestion about creating a wiki, Comprehensive documentation is key to making the project more user-friendly and accessible. Currently, the README is auto generated by AI and might not cover all the use cases or provide enough context for users. If there's more community support and interest in the project, I would be more than willing to invest time into developing a detailed wiki to enhance the user experience.

I'm thrilled to hear that you've discovered and are using this extension project, which I also utilize in my daily work. Your feedback is incredibly valuable. Thank U
